import type { CalendarEventDefinition } from "./calendar-event.types";
import { eventImages } from "./event-images";

export const vietnamEventsMetadata = {
	country: "VN",
	timeZone: "Asia/Ho_Chi_Minh",
	verifiedAt: "2026-09-18",
	scope: "Core nationwide holidays, common commemorations, traditional festivals and international observances used in Vietnam; not an exhaustive list of sector/local festivals.",
} as const;

export const vietnamEventSources = {
	valentine: {
		title: "Vietnam Tourism: Valentine's Day, 14 February",
		url: "https://vietnam.travel/things-to-do/festival-event/valentines-day",
	},
	halloween: {
		title: "Halloween in Vietnam: 31 October",
		url: "https://www.timeanddate.com/holidays/vietnam/halloween",
	},
	christmas: {
		title: "Vietnam Tourism: Giáng sinh, 24–25 December",
		url: "https://vietnam.travel/vi/things-to-do/festival-event/christmas-day",
	},
	newYearCelebrations: {
		title: "Vietnam Tourism: Christmas & New Year activities in Vietnam",
		url: "https://vietnam.travel/node/541",
	},
	aprilFools: {
		title: "Cá tháng Tư (1/4): sự tương thích văn hóa trong quá trình hội nhập",
		url: "https://thanglong.chinhphu.vn/ngay-ca-thang-tu-su-tuong-thich-van-hoa-trong-qua-trinh-hoi-nhap-10332864.htm",
	},
	happinessDay: {
		title: "United Nations: International Day of Happiness, 20 March",
		url: "https://www.un.org/en/node/54125",
	},
	environmentDay: {
		title: "UNESCO: World Environment Day, 5 June",
		url: "https://www.unesco.org/en/days/environment",
	},
	laborCode: {
		title: "Bộ luật Lao động 45/2019/QH14, Điều 112",
		url: "https://datafiles.chinhphu.vn/cpp/files/vbpq/2019/12/45.signed.pdf",
	},
	cultureDay: {
		title: "Nghị quyết 28/2026/QH16, Điều 2; hiệu lực 01/07/2026",
		url: "https://xaydungchinhsach.chinhphu.vn/toan-van-nghi-quyet-so-28-2026-qh16-ve-phat-trien-van-hoa-viet-nam-119260508142130402.htm",
	},
	nationalCommemorations: {
		title: "Hướng dẫn kỷ niệm các ngày lễ lớn năm 2026",
		url: "https://www.moc.gov.vn/vn/tin-tuc/1326/91070/huong-dan-ky-niem-cac-ngay-le-lon-va-su-kien-lich-su-quan-trong-trong-nam-2026.aspx",
	},
	doctorsDay: {
		title: "Văn phòng Chính phủ chúc mừng Ngày Thầy thuốc Việt Nam",
		url: "https://vpcp.chinhphu.vn/van-phong-chinh-phu-chuc-mung-ngay-thay-thuoc-viet-nam-11523374.htm",
	},
	youthUnion: {
		title: "Lịch sử Đoàn TNCS Hồ Chí Minh",
		url: "https://doanthanhnien.vn/gioi-thieu",
	},
	familyAndWomen: {
		title: "Kế hoạch hoạt động gia đình và phụ nữ Việt Nam",
		url: "https://bvhttdl.gov.vn/ke-hoach-lien-tich-thuc-hien-nam-gia-dinh-viet-nam-giua-bo-vhttdl-va-hoi-lhpn-viet-nam-4169.htm",
	},
	womensDay: {
		title: "Hoạt động bình đẳng giới: Quốc tế Phụ nữ 8/3",
		url: "https://dakbla.quangngai.gov.vn/upload/2007055/20260609/B%C3%A1o%20c%C3%B4ng%20t%C3%A1c%20gia%20%C4%91%C3%ACnh%20n%C4%83m%202001-2026.pdf",
	},
	childrensDay: {
		title: "Ngày Quốc tế Thiếu nhi ra đời như thế nào?",
		url: "https://tiengchuong.chinhphu.vn/ngay-quoc-te-thieu-nhi-ra-doi-nhu-the-nao-11318264.htm",
	},
	warInvalidsDay: {
		title: "Kết luận 57-KL/TW về Ngày Thương binh - Liệt sĩ",
		url: "https://xaydungchinhsach.chinhphu.vn/ket-luan-so-57-kl-tw-cua-ban-bi-thu-ve-to-chuc-cac-hoat-dong-huong-toi-ky-niem-80-nam-ngay-thuong-binh-liet-si-27-7-1947-27-7-2027-119260630163859969.htm",
	},
	teachersDay: {
		title: "Quyết định 167-HĐBT về Ngày Nhà giáo Việt Nam",
		url: "https://xaydungchinhsach.chinhphu.vn/toan-van-quyet-dinh-so-167-hdbt-ve-ngay-nha-giao-viet-nam-119231120070916265.htm",
	},
	armyDay: {
		title: "Ngày thành lập Quân đội nhân dân Việt Nam và Ngày hội Quốc phòng toàn dân",
		url: "https://vpcp.chinhphu.vn/phe-duyet-ke-hoach-to-chuc-ky-niem-cac-ngay-le-lon-11510396.htm",
	},
	nguyenTieu: {
		title: "Tết Nguyên tiêu: 15 tháng Giêng âm lịch",
		url: "https://tphcm.chinhphu.vn/khai-mac-dem-hoi-nguyen-tieu-2022-101220215221139183.htm",
	},
	hanThuc: {
		title: "Tết Hàn thực: 3/3 âm lịch",
		url: "https://vtcnews.vn/tet-han-thuc-la-ngay-gi-ar312260.html",
	},
	phatDan: {
		title: "Đại lễ Phật đản: rằm tháng Tư",
		url: "https://baochinhphu.vn/tphcm-ky-niem-dai-le-phat-dan-10278136.htm",
	},
	doanNgo: {
		title: "Tết Đoan Ngọ: 5/5 âm lịch",
		url: "https://vov.gov.vn/tet-doan-ngo-uoc-vong-ve-suc-khoe-doi-dao-dtnew-182638",
	},
	vuLan: {
		title: "Vu Lan và Rằm tháng Bảy",
		url: "https://dulichbacninh.gov.vn/kham-pha/vung-dat-con-nguoi-bac-giang/su-tich-ngay-ram-thang-bay-130.html",
	},
	trungThu: {
		title: "Tết Trung thu: 15/8 âm lịch",
		url: "https://thanglong.chinhphu.vn/khai-mac-vui-tet-trung-thu-tai-hoang-thanh-thang-long-10327420.htm",
	},
	ongTao: {
		title: "Lễ ông Công, ông Táo: 23 tháng Chạp",
		url: "https://thanglong.chinhphu.vn/nguoi-dan-tha-ca-chep-tien-ong-cong-ong-tao-ve-troi-10324020215311006.htm",
	},
} as const;

// Festival dates describe recurrence, not the full leave schedule for an employer.
export const vietnamEvents = [
	{
		id: "valentines-day",
		image: eventImages["valentines-day"],
		name: { vi: "Lễ Tình nhân (Valentine)", en: "Valentine's Day" },
		category: "international",
		date: { calendar: "solar", solar: { month: 2, day: 14 } },
		sourceIds: ["valentine"],
	},
	{
		id: "international-day-of-happiness",
		image: eventImages["international-day-of-happiness"],
		name: { vi: "Ngày Quốc tế Hạnh phúc", en: "International Day of Happiness" },
		category: "international",
		date: { calendar: "solar", solar: { month: 3, day: 20 } },
		sourceIds: ["happinessDay"],
	},
	{
		id: "april-fools-day",
		image: eventImages["april-fools-day"],
		name: { vi: "Ngày Cá tháng Tư", en: "April Fools' Day" },
		category: "international",
		date: { calendar: "solar", solar: { month: 4, day: 1 } },
		sourceIds: ["aprilFools"],
	},
	{
		id: "world-environment-day",
		image: eventImages["world-environment-day"],
		name: { vi: "Ngày Môi trường Thế giới", en: "World Environment Day" },
		category: "international",
		date: { calendar: "solar", solar: { month: 6, day: 5 } },
		sourceIds: ["environmentDay"],
	},
	{
		id: "halloween",
		image: eventImages["halloween"],
		name: { vi: "Lễ Halloween", en: "Halloween" },
		category: "international",
		date: { calendar: "solar", solar: { month: 10, day: 31 } },
		sourceIds: ["halloween"],
	},
	{
		id: "christmas-eve",
		image: eventImages["christmas-eve"],
		name: { vi: "Đêm Giáng sinh", en: "Christmas Eve" },
		category: "international",
		date: { calendar: "solar", solar: { month: 12, day: 24 } },
		sourceIds: ["christmas"],
		notes: "Mốc sự kiện là 24/12; giờ nhắc vẫn là 09:00 theo cấu hình chung của ứng dụng.",
	},
	{
		id: "christmas-day",
		image: eventImages["christmas-day"],
		name: { vi: "Lễ Giáng sinh (Noel)", en: "Christmas Day" },
		category: "international",
		date: { calendar: "solar", solar: { month: 12, day: 25 } },
		sourceIds: ["christmas"],
	},
	{
		id: "new-years-eve",
		image: eventImages["new-years-eve"],
		name: { vi: "Giao thừa Dương lịch", en: "New Year's Eve" },
		category: "international",
		date: { calendar: "solar", solar: { month: 12, day: 31 } },
		sourceIds: ["newYearCelebrations"],
		notes: "Ngày cuối năm dương lịch; giờ nhắc vẫn là 09:00, không phải thông báo lúc nửa đêm.",
	},
	{
		id: "new-year",
		image: eventImages["new-year"],
		name: { vi: "Tết Dương lịch", en: "New Year's Day" },
		category: "public-holiday",
		date: { calendar: "solar", solar: { month: 1, day: 1 } },
		sourceIds: ["laborCode"],
	},
	{
		id: "communist-party-founding",
		image: eventImages["communist-party-founding"],
		name: {
			vi: "Ngày thành lập Đảng Cộng sản Việt Nam",
			en: "Communist Party of Vietnam Founding Anniversary",
		},
		category: "commemoration",
		date: { calendar: "solar", solar: { month: 2, day: 3 } },
		sourceIds: ["nationalCommemorations"],
	},
	{
		id: "doctors-day",
		image: eventImages["doctors-day"],
		name: { vi: "Ngày Thầy thuốc Việt Nam", en: "Vietnamese Doctors' Day" },
		category: "commemoration",
		date: { calendar: "solar", solar: { month: 2, day: 27 } },
		sourceIds: ["doctorsDay"],
	},
	{
		id: "international-womens-day",
		image: eventImages["international-womens-day"],
		name: { vi: "Ngày Quốc tế Phụ nữ", en: "International Women's Day" },
		category: "international",
		date: { calendar: "solar", solar: { month: 3, day: 8 } },
		sourceIds: ["womensDay"],
	},
	{
		id: "youth-union-founding",
		image: eventImages["youth-union-founding"],
		name: {
			vi: "Ngày thành lập Đoàn TNCS Hồ Chí Minh",
			en: "Ho Chi Minh Communist Youth Union Founding Anniversary",
		},
		category: "commemoration",
		date: { calendar: "solar", solar: { month: 3, day: 26 } },
		sourceIds: ["youthUnion"],
	},
	{
		id: "reunification-day",
		image: eventImages["reunification-day"],
		name: { vi: "Ngày Giải phóng miền Nam, thống nhất đất nước", en: "Reunification Day" },
		category: "public-holiday",
		date: { calendar: "solar", solar: { month: 4, day: 30 } },
		sourceIds: ["laborCode", "nationalCommemorations"],
	},
	{
		id: "labor-day",
		image: eventImages["labor-day"],
		name: { vi: "Ngày Quốc tế Lao động", en: "International Workers' Day" },
		category: "public-holiday",
		date: { calendar: "solar", solar: { month: 5, day: 1 } },
		sourceIds: ["laborCode"],
	},
	{
		id: "dien-bien-phu-victory",
		image: eventImages["dien-bien-phu-victory"],
		name: { vi: "Ngày Chiến thắng Điện Biên Phủ", en: "Dien Bien Phu Victory Anniversary" },
		category: "commemoration",
		date: { calendar: "solar", solar: { month: 5, day: 7 } },
		sourceIds: ["nationalCommemorations"],
	},
	{
		id: "ho-chi-minh-birthday",
		image: eventImages["ho-chi-minh-birthday"],
		name: { vi: "Ngày sinh Chủ tịch Hồ Chí Minh", en: "President Ho Chi Minh's Birthday" },
		category: "commemoration",
		date: { calendar: "solar", solar: { month: 5, day: 19 } },
		sourceIds: ["nationalCommemorations"],
	},
	{
		id: "childrens-day",
		image: eventImages["childrens-day"],
		name: { vi: "Ngày Quốc tế Thiếu nhi", en: "International Children's Day" },
		category: "international",
		date: { calendar: "solar", solar: { month: 6, day: 1 } },
		sourceIds: ["childrensDay"],
	},
	{
		id: "family-day",
		image: eventImages["family-day"],
		name: { vi: "Ngày Gia đình Việt Nam", en: "Vietnamese Family Day" },
		category: "commemoration",
		date: { calendar: "solar", solar: { month: 6, day: 28 } },
		sourceIds: ["familyAndWomen"],
	},
	{
		id: "war-invalids-and-martyrs",
		image: eventImages["war-invalids-and-martyrs"],
		name: { vi: "Ngày Thương binh - Liệt sĩ", en: "War Invalids and Martyrs' Day" },
		category: "commemoration",
		date: { calendar: "solar", solar: { month: 7, day: 27 } },
		sourceIds: ["warInvalidsDay"],
	},
	{
		id: "august-revolution",
		image: eventImages["august-revolution"],
		name: { vi: "Ngày Cách mạng tháng Tám thành công", en: "August Revolution Anniversary" },
		category: "commemoration",
		date: { calendar: "solar", solar: { month: 8, day: 19 } },
		sourceIds: ["nationalCommemorations"],
	},
	{
		id: "national-day",
		image: eventImages["national-day"],
		name: { vi: "Quốc khánh Việt Nam", en: "Vietnamese National Day" },
		category: "public-holiday",
		date: { calendar: "solar", solar: { month: 9, day: 2 } },
		sourceIds: ["laborCode"],
	},
	{
		id: "vietnamese-womens-day",
		image: eventImages["vietnamese-womens-day"],
		name: { vi: "Ngày Phụ nữ Việt Nam", en: "Vietnamese Women's Day" },
		category: "commemoration",
		date: { calendar: "solar", solar: { month: 10, day: 20 } },
		sourceIds: ["familyAndWomen"],
	},
	{
		id: "teachers-day",
		image: eventImages["teachers-day"],
		name: { vi: "Ngày Nhà giáo Việt Nam", en: "Vietnamese Teachers' Day" },
		category: "commemoration",
		date: { calendar: "solar", solar: { month: 11, day: 20 } },
		sourceIds: ["teachersDay"],
	},
	{
		id: "vietnam-culture-day",
		image: eventImages["vietnam-culture-day"],
		name: { vi: "Ngày Văn hóa Việt Nam", en: "Vietnamese Culture Day" },
		category: "public-holiday",
		date: { calendar: "solar", solar: { month: 11, day: 24 } },
		validFrom: "2026-07-01",
		sourceIds: ["cultureDay"],
	},
	{
		id: "army-and-national-defense-day",
		image: eventImages["army-and-national-defense-day"],
		name: {
			vi: "Ngày thành lập Quân đội nhân dân Việt Nam / Ngày hội Quốc phòng toàn dân",
			en: "Vietnam People's Army Founding Anniversary / National Defense Day",
		},
		category: "commemoration",
		date: { calendar: "solar", solar: { month: 12, day: 22 } },
		sourceIds: ["armyDay"],
	},
	{
		id: "tet",
		image: eventImages["tet"],
		name: { vi: "Tết Nguyên đán", en: "Vietnamese Lunar New Year" },
		category: "public-holiday",
		date: { calendar: "lunar", lunar: { month: 1, day: 1, isLeapMonth: false } },
		sourceIds: ["laborCode"],
	},
	{
		id: "nguyen-tieu",
		image: eventImages["nguyen-tieu"],
		name: { vi: "Tết Nguyên tiêu (Rằm tháng Giêng)", en: "First Lunar Full Moon Festival" },
		category: "traditional",
		date: { calendar: "lunar", lunar: { month: 1, day: 15, isLeapMonth: false } },
		sourceIds: ["nguyenTieu"],
	},
	{
		id: "han-thuc",
		image: eventImages["han-thuc"],
		name: { vi: "Tết Hàn thực", en: "Cold Food Festival" },
		category: "traditional",
		date: { calendar: "lunar", lunar: { month: 3, day: 3, isLeapMonth: false } },
		sourceIds: ["hanThuc"],
		notes: "Phong tục phổ biến ở miền Bắc; không phải ngày nghỉ theo luật lao động.",
	},
	{
		id: "hung-kings",
		image: eventImages["hung-kings"],
		name: { vi: "Giỗ Tổ Hùng Vương", en: "Hung Kings Commemoration Day" },
		category: "public-holiday",
		date: { calendar: "lunar", lunar: { month: 3, day: 10, isLeapMonth: false } },
		sourceIds: ["laborCode"],
	},
	{
		id: "phat-dan",
		image: eventImages["phat-dan"],
		name: { vi: "Lễ Phật đản", en: "Buddha's Birthday" },
		category: "traditional",
		date: { calendar: "lunar", lunar: { month: 4, day: 15, isLeapMonth: false } },
		sourceIds: ["phatDan"],
		notes: "Mốc rằm tháng Tư theo lịch âm Việt Nam; lịch tổ chức đại lễ có thể khác mốc này.",
	},
	{
		id: "doan-ngo",
		image: eventImages["doan-ngo"],
		name: { vi: "Tết Đoan Ngọ", en: "Doan Ngo Festival" },
		category: "traditional",
		date: { calendar: "lunar", lunar: { month: 5, day: 5, isLeapMonth: false } },
		sourceIds: ["doanNgo"],
	},
	{
		id: "vu-lan",
		image: eventImages["vu-lan"],
		name: { vi: "Lễ Vu Lan", en: "Vu Lan Festival" },
		category: "traditional",
		date: { calendar: "lunar", lunar: { month: 7, day: 15, isLeapMonth: false } },
		sourceIds: ["vuLan"],
		notes: "Cùng ngày Rằm tháng Bảy; các nghi lễ có ý nghĩa riêng, không coi mọi nghi lễ là một sự kiện giống nhau.",
	},
	{
		id: "mid-autumn",
		image: eventImages["mid-autumn"],
		name: { vi: "Tết Trung thu", en: "Mid-Autumn Festival" },
		category: "traditional",
		date: { calendar: "lunar", lunar: { month: 8, day: 15, isLeapMonth: false } },
		sourceIds: ["trungThu"],
	},
	{
		id: "kitchen-gods",
		image: eventImages["kitchen-gods"],
		name: { vi: "Lễ ông Công, ông Táo", en: "Kitchen Gods Festival" },
		category: "traditional",
		date: { calendar: "lunar", lunar: { month: 12, day: 23, isLeapMonth: false } },
		sourceIds: ["ongTao"],
	},
	{
		id: "lunar-new-years-eve",
		image: eventImages["lunar-new-years-eve"],
		name: { vi: "Giao thừa / Tất niên", en: "Lunar New Year's Eve" },
		category: "traditional",
		date: { calendar: "lunar-new-year-offset", offsetDays: -1 },
		sourceIds: ["laborCode"],
		notes: "Quy ước ứng dụng: ngày trước mùng 1 Tết, có thể là 29 hoặc 30 tháng Chạp. Tất niên thực tế có thể được tổ chức sớm hơn; không suy ra đây là ngày nghỉ theo luật.",
	},
] as const satisfies readonly (CalendarEventDefinition & {
	sourceIds: readonly (keyof typeof vietnamEventSources)[];
})[];
